### ISSUE TITLE
Don't use the master branch as dependency.

### ISSUE THREAD

**Issue by 3rd-Eden** [cucumber-ltd/share-primus#1]
I noticed that `git://github.com/primus/primus.git#master` is used to download the version of Primus so it supports the readyStateChange events. But as it points to the master branch it could happen that I accidentally push code in to the master branch that breaks backwards compatibility as the master currently holds the code for a `2.0.0` release of Primus.

What I suggest is to set it the SHA of the last relevant commit instead of master. This way you as an author know that people will always install the version you have personally tested and prevent possible breaks in the future.

**Comment by aslakhellesoy** [comment]
@3rd-Eden I wasn't able to get it to work after primus/primus@421b847c0a2dbb98ebeb22318a3b7ac7f35b04cc - static resources were no longer served up after that. You can reproduce it by running the share-primus example.

**Comment by 3rd-Eden** [comment]
@aslakhellesoy could this be caused by https://github.com/primus/primus/issues/134

**Comment by aslakhellesoy** [comment]
@3rd-Eden yep, sounds like the same bug, and I can also confirm that primus/primus@aa0debc738a066c532bacc04f8652680f3f17110 works a treat!
