### ISSUE TITLE
Having trouble getting it to build:

### ISSUE THREAD

**Issue by thompsonbill** [cucumber-ltd/share-primus#5]
``` script
$ npm run-script build-sharejs

> share-primus@0.0.2 build-sharejs /home/eric/share-primus
> cd node_modules/share && curl -s https://github.com/share/ShareJS/pull/276.patch | patch -p1 && make webclient UGLIFY="../../node_modules/.bin/uglifyjs -d WEB=true"

patching file lib/client/doc.js
Hunk #1 FAILED at 216.
1 out of 1 hunk FAILED -- saving rejects to file lib/client/doc.js.rej
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by aslakhellesoy** [comment]
@thompsonbill can you try again with 0.0.3?

**Comment by thompsonbill** [comment]
Sorry for the delay in responding, I was on holidays. It builds fine for me now.

However I am getting a perpetual Connecting... on every browser I tried (Chrome 25, Chrome 32, and Firefox)

Error {} share.uncompressed.js:675
MicroEvent.emit share.uncompressed.js:675
(anonymous function) share-primus.js:29
emit primus.js:49
mine primus.js:1658
incoming primus.js:1523
decoding primus.js:624
decoder primus.js:1408
message primus.js:609
emit primus.js:49
timeout primus.js:1240
Uncaught Error: Cannot transition directly from undefined to connected share.uncompressed.js:1961
Connection._setState share.uncompressed.js:1961
Connection.handleMessage share.uncompressed.js:1892
(anonymous function) share-primus.js:27
emit primus.js:49
mine primus.js:1658
incoming primus.js:1523
decoding primus.js:624
decoder primus.js:1408
message primus.js:609
emit primus.js:49
timeout

**Comment by aslakhellesoy** [comment]
It sounds like you are using an incompatible version of Share.js. You need `v0.7.0-alpha13` or newer. What version are you on?

Have you tried running the example? Does that work for you?

**Comment by thompsonbill** [comment]
0.7.0-alpha13 is the version I'm on; this is testing the example.  I tried installing it from both npm and also I manually put my working ShareJs (tip of master) in share-primus/node_modules. Same Error. :/ I'm on node 0.10 on Fedora. Odd indeed.
